spring.application.name=student-rest-api
server.port=8080

# Cloud Deployment Config (Default to local if env vars are missing)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/student_api_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Vajjhasai@777}

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
