services:
  - type: web
    name: auth-backend
    env: docker
    rootDir: backend/auth-system
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: NEON_DB_URL
        sync: false
      - key: NEON_DB_USERNAME
        sync: false
      - key: NEON_DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
